const securityPlusAcronyms = [
	{ acro: "ACL", full: "Access Control List", category: "Access Control" },
	{ acro: "AES", full: "Advanced Encryption Standard", category: "Cryptography" },
	{ acro: "APT", full: "Advanced Persistent Threat", category: "Threats" },
	{ acro: "CIA", full: "Confidentiality, Integrity, Availability", category: "Security Concepts" },
	{ acro: "DAC", full: "Discretionary Access Control", category: "Access Control" },
	{ acro: "DDoS", full: "Distributed Denial of Service", category: "Threats" },
	{ acro: "DEP", full: "Data Execution Prevention", category: "Security Mechanisms" },
	{ acro: "DES", full: "Data Encryption Standard", category: "Cryptography" },
	{ acro: "DNS", full: "Domain Name System", category: "Networking" },
	{ acro: "DoS", full: "Denial of Service", category: "Threats" },
	{ acro: "DLP", full: "Data Loss Prevention", category: "Data Security" },
	{ acro: "FIM", full: "File Integrity Monitoring", category: "Monitoring" },
	{ acro: "GPO", full: "Group Policy Object", category: "Access Control" },
	{ acro: "HIDS", full: "Host based Intrusion Detection System", category: "Monitoring" },
	{ acro: "HMAC", full: "Hash Based Message Authentication Code", category: "Cryptography" },
	{ acro: "IAM", full: "Identity and Access Management", category: "Access Control" },
	{ acro: "IDS", full: "Intrusion Detection System", category: "Monitoring" },
	{ acro: "IPS", full: "Intrusion Prevention System", category: "Monitoring" },
	{ acro: "IR", full: "Incident Response", category: "Security Operations" },
	{ acro: "KDC", full: "Key Distribution Center", category: "Cryptography" },
	{ acro: "LDAP", full: "Lightweight Directory Access Protocol", category: "Access Control" },
	{ acro: "MAC", full: "Mandatory Access Control", category: "Access Control" },
	{ acro: "MD5", full: "Message Digest 5", category: "Cryptography" },
	{ acro: "MITM", full: "Man In The Middle", category: "Threats" },
	{ acro: "NAC", full: "Network Access Control", category: "Networking" },
	{ acro: "NAT", full: "Network Address Translation", category: "Networking" },
	{ acro: "NIDS", full: "Network based Intrusion Detection System", category: "Monitoring" },
	{ acro: "NTLM", full: "NT LAN Manager", category: "Authentication" },
	{ acro: "OCSP", full: "Online Certificate Status Protocol", category: "Cryptography" },
	{ acro: "OTP", full: "One Time Password", category: "Authentication" },
	{ acro: "PAP", full: "Password Authentication Protocol", category: "Authentication" },
	{ acro: "PEAP", full: "Protected Extensible Authentication Protocol", category: "Authentication" },
	{ acro: "PKI", full: "Public Key Infrastructure", category: "Cryptography" },
	{ acro: "RBAC", full: "Role Based Access Control", category: "Access Control" },
	{ acro: "RDP", full: "Remote Desktop Protocol", category: "Networking" },
	{ acro: "RSA", full: "Rivest Shamir Adleman", category: "Cryptography" },
	{ acro: "SAML", full: "Security Assertion Markup Language", category: "Authentication" },
	{ acro: "SHA", full: "Secure Hash Algorithm", category: "Cryptography" },
	{ acro: "SIEM", full: "Security Information and Event Management", category: "Monitoring" },
	{ acro: "VPN", full: "Virtual Private Network", category: "Networking" },
  ];
  