const securityPlusAcronyms = [
	{ acro: "ACL", full: "Access Control List", category: "Access Control", difficulty: "easy" },
	{ acro: "AES", full: "Advanced Encryption Standard", category: "Cryptography", difficulty: "easy" },
	{ acro: "APT", full: "Advanced Persistent Threat", category: "Threats", difficulty: "medium" },
	{ acro: "CIA", full: "Confidentiality Integrity Availability", category: "Security Concepts", difficulty: "medium" },
	{ acro: "DAC", full: "Discretionary Access Control", category: "Access Control", difficulty: "easy" },
	{ acro: "DDoS", full: "Distributed Denial of Service", category: "Threats", difficulty: "medium" },
	{ acro: "DEP", full: "Data Execution Prevention", category: "Security Mechanisms", difficulty: "medium" },
	{ acro: "DES", full: "Data Encryption Standard", category: "Cryptography", difficulty: "medium" },
	{ acro: "DNS", full: "Domain Name System", category: "Networking", difficulty: "easy" },
	{ acro: "DoS", full: "Denial of Service", category: "Threats", difficulty: "easy" },
	{ acro: "DLP", full: "Data Loss Prevention", category: "Data Security", difficulty: "medium" },
	{ acro: "FIM", full: "File Integrity Monitoring", category: "Monitoring", difficulty: "hard" },
	{ acro: "GPO", full: "Group Policy Object", category: "Access Control", difficulty: "easy" },
	{ acro: "HIDS", full: "Host Intrusion Detection System", category: "Monitoring", difficulty: "medium" },
	{ acro: "HMAC", full: "Hash Message Authentication Code", category: "Cryptography", difficulty: "hard" },
	{ acro: "IAM", full: "Identity Access Management", category: "Access Control", difficulty: "hard" },
	{ acro: "IDS", full: "Intrusion Detection System", category: "Monitoring", difficulty: "medium" },
	{ acro: "IPS", full: "Intrusion Prevention System", category: "Monitoring", difficulty: "medium" },
	{ acro: "IR", full: "Incident Response", category: "Security Operations", difficulty: "easy" },
	{ acro: "KDC", full: "Key Distribution Center", category: "Cryptography", difficulty: "medium"},
	{ acro: "LDAP", full: "Lightweight Directory Access Protocol", category: "Access Control", difficulty: "medium" },
	{ acro: "MAC", full: "Mandatory Access Control", category: "Access Control", difficulty: "hard" },
	{ acro: "MD5", full: "Message Digest 5", category: "Cryptography", difficulty: "hard" },
	{ acro: "MITM", full: "Man In The Middle", category: "Threats", difficulty: "easy" },
	{ acro: "NAC", full: "Network Access Control", category: "Networking", difficulty: "medium" },
	{ acro: "NAT", full: "Network Address Translation", category: "Networking", difficulty: "easy" },
	{ acro: "NIDS", full: "Network Intrusion Detection System", category: "Monitoring", difficulty: "medium" },
	{ acro: "OCSP", full: "Online Certificate Status Protocol", category: "Cryptography", difficulty: "hard" },
	{ acro: "OTP", full: "One Time Password", category: "Authentication", difficulty: "medium" },
	{ acro: "PAP", full: "Password Authentication Protocol", category: "Authentication", difficulty: "hard" },
	{ acro: "PEAP", full: "Protected Extensible Authentication Protocol", category: "Authentication", difficulty: "hard" },
	{ acro: "PKI", full: "Public Key Infrastructure", category: "Cryptography", difficulty: "easy" },
	{ acro: "RBAC", full: "Role Based Access Control", category: "Access Control", difficulty: "medium" },
	{ acro: "RDP", full: "Remote Desktop Protocol", category: "Networking", difficulty: "easy" },
	{ acro: "RSA", full: "Rivest Shamir Adleman", category: "Cryptography", difficulty: "hard" },
	{ acro: "SAML", full: "Security Assertion Markup Language", category: "Authentication", difficulty: "hard" },
	{ acro: "SHA", full: "Secure Hash Algorithm", category: "Cryptography", difficulty: "easy" },
	{ acro: "SIEM", full: "Security Information Event Management", category: "Monitoring", difficulty: "easy" },
	{ acro: "VPN", full: "Virtual Private Network", category: "Networking", difficulty: "easy" },
	{ acro: "MFA", full: "Multi Factor Authentication", category: "Authentication", difficulty: "easy" },
	{ acro: "UEBA", full: "User Entity Behavior Analytics", category: "Monitoring", difficulty: "medium" },
	{ acro: "SFTP", full: "Secure File Transfer Protocol", category: "Networking", difficulty: "easy" },
	{ acro: "TTP", full: "Tactics Techniques Procedures", category: "Threats", difficulty: "medium" },
	{ acro: "FDE", full: "Full Disk Encryption", category: "Cryptography", difficulty: "hard" },
	{ acro: "SDN", full: "Software Defined Networking", category: "Networking", difficulty: "hard" },
	{ acro: "PDU", full: "Protocol Data Unit", category: "Networking", difficulty: "hard" },
	{ acro: "SOAR", full: "Security Orchestration Automation Response", category: "Security Operations", difficulty: "hard" },
	{ acro: "UEFI", full: "Unified Extensible Firmware Interface", category: "Security Mechanisms", difficulty: "hard" },
	{ acro: "ABAC", full: "Attribute Based Access Control", category: "Access Control", difficulty: "medium" },
	{ acro: "SPOF", full: "Single Point Of Failure", category: "Security Concepts", difficulty: "medium" },
	{ acro: "DAS", full: "Direct Attached Storage", category: "Storage", difficulty: "medium" },
	{ acro: "RTO", full: "Recovery Time Objective", category: "Business Continuity", difficulty: "medium" },
	{ acro: "MTTR", full: "Mean Time To Repair", category: "Security Operations", difficulty: "easy" },
	{ acro: "MTTF", full: "Mean Time To Failure", category: "Security Operations", difficulty: "easy" },
	{ acro: "BCP", full: "Business Continuity Plan", category: "Business Continuity", difficulty: "medium" },
	{ acro: "BIA", full: "Business Impact Analysis", category: "Business Continuity", difficulty: "medium" },
	{ acro: "SLA", full: "Service Level Agreement", category: "Security Concepts", difficulty: "easy" },
	{ acro: "RAID", full: "Redundant Array Independent Disks", category: "Storage", difficulty: "medium" },
	{ acro: "SYN", full: "Synchronize Sequence Number", category: "Networking", difficulty: "medium" },
	{ acro: "SSO", full: "Single Sign On", category: "Authentication", difficulty: "easy" },
	{ acro: "TLS", full: "Transport Layer Security", category: "Cryptography", difficulty: "medium" },
	{ acro: "UPS", full: "Uninterruptible Power Supply", category: "Physical Security", difficulty: "medium" },
	{ acro: "WAF", full: "Web Application Firewall", category: "Security Mechanisms", difficulty: "medium" },
	{ acro: "VLAN", full: "Virtual Local Area Network", category: "Networking", difficulty: "easy" },
	{ acro: "FQDN", full: "Fully Qualified Domain Name", category: "Networking", difficulty: "easy" },
	{ acro: "RFI", full: "Remote File Inclusion", category: "Threats", difficulty: "medium" },
	{ acro: "UAT", full: "User Acceptance Testing", category: "Testing", difficulty: "medium" },
	{ acro: "CTR", full: "Counter Mode Encryption", category: "Cryptography", difficulty: "medium" },
	{ acro: "EFS", full: "Encrypting File System", category: "Cryptography", difficulty: "medium" },
	{ acro: "SMS", full: "Short Message Service", category: "Networking", difficulty: "easy" },
	{ acro: "HSM", full: "Hardware Security Module", category: "Cryptography", difficulty: "hard" },
	{ acro: "GRC", full: "Governance Risk Compliance", category: "Compliance", difficulty: "medium" },
	{ acro: "MBR", full: "Master Boot Record", category: "Security Mechanisms", difficulty: "medium" },
	{ acro: "PST", full: "Personal Storage Table", category: "Storage", difficulty: "medium" },
	{ acro: "TGS", full: "Ticket Granting Service", category: "Authentication", difficulty: "hard" },
	{ acro: "IoT", full: "Internet Of Things", category: "Networking", difficulty: "easy" },
	{ acro: "ALE", full: "Annual Loss Expectancy", category: "Risk Management", difficulty: "medium" },
	{ acro: "ARO", full: "Annual Rate Occurrence", category: "Risk Management", difficulty: "medium" },
	{ acro: "MTD", full: "Maximum Tolerable Downtime", category: "Business Continuity", difficulty: "hard" },
	{ acro: "MOA", full: "Memorandum Of Agreement", category: "Compliance", difficulty: "hard" },
	{ acro: "MOU", full: "Memorandum Of Understanding", category: "Compliance", difficulty: "hard" },
	{ acro: "CSRF", full: "Cross Site Request Forgery", category: "Threats", difficulty: "hard" },
	{ acro: "XSS", full: "Cross Site Scripting", category: "Threats", difficulty: "medium" },
	{ acro: "YARA", full: "Yet Another Recursive Acronym", category: "Monitoring", difficulty: "hard" },
	{ acro: "SCAP", full: "Security Content Automation Protocol", category: "Compliance", difficulty: "hard" },
	{ acro: "DRM", full: "Digital Rights Management", category: "Compliance", difficulty: "medium" },
];